### ISSUE TITLE
Fix error when logout a user

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/Rails-Graphql-React-Apollo#27]
Maybe in the `MenuTopics` component

![image](https://user-images.githubusercontent.com/12489333/41824439-f6b27e02-77dd-11e8-997b-a5cf7274353c.png)

**Comment by alfredrumss** [comment]
@CharlyJazz  aqui te tengo un issue mas interesante, ¿me bloqueaste en telegram?  D:

Necesito comunicarme contigo, pasame un correo para pasarte una informacion.
