### ISSUE TITLE
Can not access data from graphQL API

### ISSUE THREAD

**Issue by YengTsan** [CharlyJazz/Rails-Graphql-React-Apollo#28]
Hello authors,

First, thanks for sharing this project, I learn a lot from this repo.
I am a rails developer, learning about GraphQL and React.

However, I run into a problem. After cloning the project and running rails & react successfully,
I try to open the react from `http://localhost:3001/`.
Then, I got `TypeError: Cannot read property 'map' of undefined` in the browser.

And in the rails console, I got the following:

`Started OPTIONS "/graphql" for 127.0.0.1 at 2018-08-13 00:16:32 +0800
ActionController::RoutingError (No route matches [OPTIONS] "/graphql"):`

Do you run into this issue? or I did something wrong ?
Thanks for your sharing again. Looking forward to receive your reply. 
Thx

**Comment by CharlyJazz** [comment]
Maybe you need create run the seed commando to populate the database. The command takes a couple of minutes because it is quite dated.

Did you run `rails db:schema:load && rails db:seed` ?

**Comment by YengTsan** [comment]
Thanks for your reply.

I have successfully run the rails app and the react app locally. 
My trouble is about CORS, and I fix it by using https://github.com/cyu/rack-cors.

Thanks again, wish you a nice day : D

**Comment by CharlyJazz** [comment]
I will continue working in the Front End soon, but at the moment I am very busy working
