### ISSUE TITLE
Create a page to create Post

### ISSUE THREAD

**Issue by CharlyJazz** [CharlyJazz/Rails-Graphql-React-Apollo#5]
Create this section in the `createPost` container, and evaluate which library to use to generate the body of the post as [draftfjs](https://draftjs.org/)

**Comment by extrasad** [comment]
@CharlyJazz Activo pa hacer ese issue

**Comment by Wgil** [comment]
Some drafts examples: http://draftjs-examples.herokuapp.com/
Another library built upon draftjs https://github.com/sstur/react-rte
