### ISSUE TITLE
Update readme file

### ISSUE THREAD

**Issue by Wgil** [CharlyJazz/Rails-Graphql-React-Apollo#6]
- Add an introduction describing the project.
- Add required dependencies and versions.
- Add setup instructions.
- Add Waffle

**Comment by andres-uris** [comment]
I'm working in this issue

**Comment by Villanuevand** [comment]
I can recommend this [readme template]
 (https://gist.github.com/Villanuevand/6386899f70346d4580c723232524d35a) made by myself

**Comment by andres-uris** [comment]
@Villanuevand  Hey the template is really good. I will do the readme inspire on it. Thank you

**Comment by Villanuevand** [comment]
@andres-uris 
You're welcome folk , im glad to read that... 

Good luck!
